@startuml

left to right direction

hide circle

title Conceptual Classes Diagram 

Class Location {
    name
}

Class Department {
    name
}

Class Employee {
    name
    job
    hiredate
    sal
    comm
}

Class Manager {
}

Employee <|-- Manager

Employee "1" <-- "+" Manager : manage

Employee "+" --> "1" Department : work

Location"1" o-- "+"Department


@enduml
